# Generated by Django 5.1.5 on 2025-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hashtag',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
